#!/usr/bin/python

import pycurl
import pprint
import json
from io import BytesIO

c = pycurl.Curl()
data = BytesIO()

##--You must paste your generated keys <CLOUD-API> and <KEY>
c.setopt(c.URL, '<CLOUD-API>')
c.setopt(pycurl.HTTPHEADER, ['Authorization: OAuth <KEY>'])
c.setopt(c.WRITEFUNCTION, data.write)
c.perform()

d = json.loads(data.getvalue())
## Downwrited string you can change on any metric of Yandex API. In my case its result a free space on YandexDisk
pprint.pprint((d['total_space']-d['used_space'])/1024/1024)
